# Generates vectors.h: reference values computed with the Python "cryptography" package.
import os, hashlib, hmac
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF, HKDFExpand
from cryptography.hazmat.primitives import hashes, serialization

rnd = __import__("random").Random(1234)
def rb(n): return bytes(rnd.getrandbits(8) for _ in range(n))
def c(b): return "{" + ",".join("0x%02x" % x for x in b) + "}"
out = ["// Generated by gen_vectors.py with the Python cryptography package. Do not edit.", "#pragma once", "#include <stdint.h>", "#include <stddef.h>"]

# X25519
out.append("struct XVec { uint8_t priv[32], peer[32], shared[32]; };")
xs = []
for i in range(8):
    a = rb(32); peer_priv = X25519PrivateKey.from_private_bytes(rb(32))
    peer = peer_priv.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    sh = X25519PrivateKey.from_private_bytes(a).exchange(X25519PublicKey.from_public_bytes(peer))
    xs.append("{%s,%s,%s}" % (c(a), c(peer), c(sh)))
out.append("static const XVec kX25519[] = {%s};" % ",".join(xs))

# AES-256-GCM
out.append("struct GVec { uint8_t key[32], iv[12]; uint8_t aad[20]; size_t aadLen; uint8_t pt[70]; size_t len; uint8_t ct[70]; uint8_t tag[16]; };")
gs = []
for aadLen, ln in [(0,0),(0,16),(10,32),(20,70),(13,1),(0,58),(10,33)]:
    k = rb(32); iv = rb(12); aad = rb(aadLen); pt = rb(ln)
    ct = AESGCM(k).encrypt(iv, pt, aad if aadLen else None)
    gs.append("{%s,%s,%s,%d,%s,%d,%s,%s}" % (c(k), c(iv), c(aad.ljust(20, b"\0")), aadLen, c(pt.ljust(70, b"\0")), ln, c(ct[:-16].ljust(70, b"\0")), c(ct[-16:])))
out.append("static const GVec kGcm[] = {%s};" % ",".join(gs))

# SHA-256 / HMAC / HKDF
msg = rb(200)
out.append("static const uint8_t kShaMsg[200] = %s;" % c(msg))
out.append("static const uint8_t kShaDigest[3][32] = {%s,%s,%s};" % (c(hashlib.sha256(msg[:0]).digest()), c(hashlib.sha256(msg[:55]).digest()), c(hashlib.sha256(msg).digest())))
key = rb(100)
out.append("static const uint8_t kHmacKey[100] = %s;" % c(key))
out.append("static const uint8_t kHmac[2][32] = {%s,%s};" % (c(hmac.new(key[:20], msg, hashlib.sha256).digest()), c(hmac.new(key, msg[:10], hashlib.sha256).digest())))
salt = rb(32); ikm = rb(64)
prk = hmac.new(salt, ikm, hashlib.sha256).digest()
okm = HKDFExpand(hashes.SHA256(), 80, b"link test").derive(prk)
out.append("static const uint8_t kHkdfSalt[32] = %s;" % c(salt))
out.append("static const uint8_t kHkdfIkm[64] = %s;" % c(ikm))
out.append("static const uint8_t kHkdfPrk[32] = %s;" % c(prk))
out.append("static const uint8_t kHkdfOkm[80] = %s;" % c(okm))
open("vectors.h", "w").write("\n".join(out) + "\n")
print("ok")
