# Builds and runs the SecurePair host tests (requires: python -m pip install ziglang).
# vectors.h is generated by gen_vectors.py (requires: python -m pip install cryptography).
$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$src = Join-Path $root "src"
$exe = Join-Path $env:TEMP "securepair_test.exe"
$sources = @(
  "$PSScriptRoot\test_securepair.cpp",
  "$src\SecurePair.cpp",
  "$src\SecureLink.cpp",
  "$src\internal\Crypto.cpp",
  "$src\internal\Datagram.cpp",
  "$src\internal\CryptoPortable.cpp",
  "$src\internal\Protocol.cpp",
  "$src\internal\PeerTable.cpp",
  "$src\internal\PairEngine.cpp",
  "$src\internal\Seal.cpp",
  "$src\internal\PlainNvsStorage.cpp",
  "$src\internal\SealedNvsStorage.cpp",
  "$src\storage\NvsPairStorage.cpp"
)
python -m ziglang c++ -std=c++17 -O2 -Wall -Wextra -I $src -I $PSScriptRoot @sources -o $exe
if ($LASTEXITCODE -ne 0) { Write-Host "Build failed"; exit 1 }
& $exe
exit $LASTEXITCODE
